### ISSUE TITLE
vercel 部署无法正常启动

### ISSUE THREAD

**Issue by hl128k** [yelochick/deeplx-lb#2]
vercel日志错误信息
```
TypeError: Cannot convert undefined or null to object
at Function.keys (<anonymous>)
at initialize (file:///var/task/app.js:74:26)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async file:///var/task/app.js:212:1
Node.js process exited with exit status: 1. The logs above can help with debugging the issue.
INIT_REPORT Init Duration: 1118.71 ms	Phase: init	Status: error	Error Type: Runtime.ExitError
TypeError: Cannot convert undefined or null to object
at Function.keys (<anonymous>)
at initialize (file:///var/task/app.js:74:26)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async file:///var/task/app.js:212:1
Node.js process exited with exit status: 1. The logs above can help with debugging the issue.
INIT_REPORT Init Duration: 1221.73 ms	Phase: invoke	Status: error	Error Type: Runtime.ExitError
```
环境配置:
![图片](https://github.com/yelochick/deeplx-lb/assets/19748616/cfdafff4-5431-44b1-8bdd-67339ded72c6)

**Comment by xiaozhang959** [comment]
佬，你的问题解决了嘛？   我的部署也报错了

**Comment by hl128k** [comment]
我看代码感觉是获取环境变量错误

**Comment by bebestmaple** [comment]
![image](https://github.com/yelochick/deeplx-lb/assets/7425640/96e59fed-d7ee-4633-a683-56484ede462a)
有需要的，可以自行改动。我提个pr看看大佬接受不接受
